---
title: "Descriptive analysis MatchBoots"
format: docx
execute:
  echo: false
editor: visual
---

## Table 1 parameters
  
```{r}
#| output: false
#| warning: false

library(gtsummary)
library(htmlwidgets)
library(ggplot2)
library(cowplot)
library(data.table)
library(stringr)
```

```{r}
#| output: false

parent_wd <- dirname(getwd())
load(file.path(parent_wd, "g_parameters", "parameters.RData"))

# bnch <- qs::qread(file.path(parent_wd, "g_results", "Laptop 1", paste0("combined_benchmarks", ".qs")))
bnch <- qs::qread(file.path(parent_wd, "g_results", "Server 1", paste0("combined_benchmarks", ".qs")))
```

```{r}
#| output: false

bnch$algo <- factor(bnch$algo, levels = c("Naive", "Hash", "Threshold"))
bnch$cm <- factor(bnch$cm, levels = sort(unique(bnch$cm)))
bnch$mem_alloc <- bnch$mem_alloc / 1024 ^ 2
bnch$exp <- as.factor(bnch$exp)
bnch$threshold_to_use <- factor(bnch$threshold_to_use)
bnch[, secondary_memory_usage := (size_intermediate + size_output) / 1024]

bnch[, match_vars_label := data.table::fcase(match_vars_label == "Mat1", "Age exact + Uniform",
                                             match_vars_label == "Mat2", "Age +=1 + Uniform",
                                             match_vars_label == "Mat3", "Age exact + Normal")]
bnch[, match_vars_label := factor(match_vars_label, levels = c("Age exact + Uniform", "Age +=1 + Uniform",
                                                               "Age exact + Normal"))]

bnch[, samp_schema_label := data.table::fcase(samp_schema_label == "S1", "Sample 1 cm to each exposed",
                                              samp_schema_label == "SN", "Take all cm to each exposed",
                                              samp_schema_label == "S1B10SExp", "Sample 1 cm to each exposed and take 10 bootstrap sampling from the exposed",
                                              samp_schema_label == "S1B10SUoO", "Sample 1 cm to each exposed and take 10 bootstrap sampling from all UoO")]
bnch[, samp_schema_label := factor(samp_schema_label,
                                   levels = c("Sample 1 cm to each exposed", "Take all cm to each exposed",
                                              "Sample 1 cm to each exposed and take 10 bootstrap sampling from the exposed",
                                              "Sample 1 cm to each exposed and take 10 bootstrap sampling from all UoO"))]

bnch[, cores_label := data.table::fcase(cores_label == "C1", "Use 1 thread",
                                        cores_label == "Cdef", "Use half the threads present in the CPU")]

bnch[, threshold_to_use := factor(threshold_to_use, levels = c(NA, 1, "half", "max", "double"))]


```

```{r}
#| echo: false
bnch %>% tbl_summary(by = exp,
                     include = c(algo, cm, threshold_to_use, match_vars_label,
                                 samp_schema_label, cores_label),
                     label = list(
                       algo ~ "Algorithm",
                       cm ~ "Additional candidate matches proportion",
                       threshold_to_use ~ "Threshold to use",
                       match_vars_label ~ "Matching rules and Variable distributions",
                       samp_schema_label ~ "Sampling of candidate matches and bootstrap schema",
                       cores_label ~ "Number of cores used")
                     ) %>%
  as_gt()
```

## Table 1 metrics

```{r}
#| echo: false
bnch %>% mutate(time1 = time, mem_alloc1 = mem_alloc, secondary_memory_usage1 = secondary_memory_usage,
                time2 = time, mem_alloc2 = mem_alloc, secondary_memory_usage2 = secondary_memory_usage) %>% 
  tbl_summary(by = exp,
                     include = c(time, time1, time2, mem_alloc, mem_alloc1, mem_alloc2, secondary_memory_usage,
                                 secondary_memory_usage1, secondary_memory_usage2),
                     statistic = list(
                       time ~ "{min} / {max}",
                       time1 ~ "{p25} / {median} / {p75}",
                       time2 ~ "{mean} / {sd}",
                       mem_alloc ~ "{min} / {max}",
                       mem_alloc1 ~ "{p25} / {median} / {p75}",
                       mem_alloc2 ~ "{mean} / {sd}",
                       secondary_memory_usage ~ "{min} / {max}",
                       secondary_memory_usage1 ~ "{p25} / {median} / {p75}",
                       secondary_memory_usage2 ~ "{mean} / {sd}"
                     ),
                     label = list(
                       time ~ "Time (s) (Min, Max)",
                       time1 ~ "Time (s) (25%, Median, 75%)",
                       time2 ~ "Time (s) (Mean, SD)",
                       mem_alloc ~ "Memory allocation (MB) (Min, Max)",
                       mem_alloc1 ~ "Memory allocation (MB) (25%, Median, 75%)",
                       mem_alloc2 ~ "Memory allocation (MB) (Mean, SD)",
                       secondary_memory_usage ~ "Secondary memory usage (KB) (Min, Max)",
                       secondary_memory_usage1 ~ "Secondary memory usage (KB) (25%, Median, 75%)",
                       secondary_memory_usage2 ~ "Secondary memory usage (KB) (Mean, SD)")
                     ) %>%
    modify_footnote(all_stat_cols(FALSE) ~ NA) %>%
  as_gt()
```

## Algorithm

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = exp, y = time, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = exp, y = time, fill = cm)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = exp, y = time, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = exp, y = time, fill = cm)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = exp, y = mem_alloc, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = exp, y = mem_alloc, fill = cm)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = exp, y = mem_alloc, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = exp, y = mem_alloc, fill = cm)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = exp, y = secondary_memory_usage, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = exp, y = secondary_memory_usage, fill = cm)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = exp, y = secondary_memory_usage, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = exp, y = secondary_memory_usage, fill = cm)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

## Candidate matches

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = cm, y = time, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = cm, y = time, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = cm, y = time, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = cm, y = time, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = cm, y = mem_alloc, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = cm, y = mem_alloc, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = cm, y = mem_alloc, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = cm, y = mem_alloc, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = cm, y = secondary_memory_usage, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = cm, y = secondary_memory_usage, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = cm, y = secondary_memory_usage, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = cm, y = secondary_memory_usage, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

## Threshold to use

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = threshold_to_use, y = time, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = threshold_to_use, y = time, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = threshold_to_use, y = time, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = threshold_to_use, y = time, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = threshold_to_use, y = mem_alloc, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = threshold_to_use, y = mem_alloc, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = threshold_to_use, y = mem_alloc, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = threshold_to_use, y = mem_alloc, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = threshold_to_use, y = secondary_memory_usage, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = threshold_to_use, y = secondary_memory_usage, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = threshold_to_use, y = secondary_memory_usage, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = threshold_to_use, y = secondary_memory_usage, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

## Matching rules and Variable distributions

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = match_vars_label, y = time, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = match_vars_label, y = time, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = match_vars_label, y = time, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = match_vars_label, y = time, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = match_vars_label, y = mem_alloc, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = match_vars_label, y = mem_alloc, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = match_vars_label, y = mem_alloc, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = match_vars_label, y = mem_alloc, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = match_vars_label, y = secondary_memory_usage, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = match_vars_label, y = secondary_memory_usage, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = match_vars_label, y = secondary_memory_usage, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = match_vars_label, y = secondary_memory_usage, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

## Sampling of candidate matches and bootstrap schema

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = samp_schema_label, y = time, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
exp_box <- ggplot(bnch, aes(x = samp_schema_label, y = time, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
algo_vio <- ggplot(bnch, aes(x = samp_schema_label, y = time, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
exp_vio <- ggplot(bnch, aes(x = samp_schema_label, y = time, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = samp_schema_label, y = mem_alloc, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
exp_box <- ggplot(bnch, aes(x = samp_schema_label, y = mem_alloc, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
algo_vio <- ggplot(bnch, aes(x = samp_schema_label, y = mem_alloc, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
exp_vio <- ggplot(bnch, aes(x = samp_schema_label, y = mem_alloc, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = samp_schema_label, y = secondary_memory_usage, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
exp_box <- ggplot(bnch, aes(x = samp_schema_label, y = secondary_memory_usage, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
algo_vio <- ggplot(bnch, aes(x = samp_schema_label, y = secondary_memory_usage, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
exp_vio <- ggplot(bnch, aes(x = samp_schema_label, y = secondary_memory_usage, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 20))
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

## Number of cores used

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = cores_label, y = time, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = cores_label, y = time, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = cores_label, y = time, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = cores_label, y = time, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = cores_label, y = mem_alloc, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = cores_label, y = mem_alloc, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = cores_label, y = mem_alloc, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = cores_label, y = mem_alloc, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
algo_box <- ggplot(bnch, aes(x = cores_label, y = secondary_memory_usage, fill = algo)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_box <- ggplot(bnch, aes(x = cores_label, y = secondary_memory_usage, fill = exp)) + 
    geom_boxplot() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.775), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
algo_vio <- ggplot(bnch, aes(x = cores_label, y = secondary_memory_usage, fill = algo)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
exp_vio <- ggplot(bnch, aes(x = cores_label, y = secondary_memory_usage, fill = exp)) + 
    geom_violin() +
    stat_summary(fun = mean, geom = "point", shape = 20, position = position_dodge(0.9), size = 4, color = "red",
                show.legend = FALSE) +
  scale_y_log10(labels = scales::label_comma())
plot_grid(algo_box, algo_vio, exp_box, exp_vio, labels = c("A", "B", "C", "D"), ncol = 2, nrow = 2)
```

```{r fig.height=8,fig.width=16}
#| echo: false
car::powerTransform(bnch$time, family="bcPower")
plot(sort(bnch$time))
plot(log(sort(bnch$time)))
```
